name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: '1.x'

    - name: Create Release
      run: |
        deno run --allow-net --allow-read - <<EOF
        const token = Deno.env.get("GITHUB_TOKEN");
        if (!token) {
          console.error("GitHub token is missing.");
          Deno.exit(1);
        }

        const response = await fetch("https://api.github.com/repos/artpani4/notion/releases", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${token}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            tag_name: "v1.0.0",
            name: "Release v1.0.0",
            body: "Release description",
          }),
        });

        if (response.status === 201) {
          console.log("Release created successfully.");
        } else {
          console.error("Failed to create release.");
          Deno.exit(1);
        }
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
